# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Stock')),
            ],
        ),
    ]
