# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('speciesID', models.AutoField(primary_key=True, serialize=False)),
                ('genName', models.CharField(max_length=50)),
                ('sciName', models.CharField(max_length=50)),
                ('genDescription', models.TextField(max_length=400)),
                ('genImgResID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesInstance',
            fields=[
                ('speciesIntanceID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('siteSpecificDescription', models.TextField(max_length=400)),
                ('siteSpecificImgResID', models.IntegerField()),
                ('dateCreated', models.DateField()),
                ('dateModified', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plantcollection',
            name='collectionID',
        ),
        migrations.RemoveField(
            model_name='plantcollection',
            name='plantID',
        ),
        migrations.AlterField(
            model_name='collection',
            name='collectionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='PlantCollection',
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='collectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Collection'),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='speciesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Species'),
        ),
    ]
