# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20170313_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('siteSpecificDescription', models.TextField(max_length=400)),
                ('siteSpecificImgResID', models.IntegerField()),
                ('dateCreated', models.DateField()),
                ('dateModified', models.DateField()),
                ('collectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Collection')),
                ('speciesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Species')),
            ],
        ),
        migrations.RemoveField(
            model_name='speciesinstance',
            name='collectionID',
        ),
        migrations.RemoveField(
            model_name='speciesinstance',
            name='speciesID',
        ),
        migrations.DeleteModel(
            name='SpeciesInstance',
        ),
    ]
